# fly.toml app configuration file generated for rw-8-4-4-ssr-rsc-bold-moon-3936 on 2025-01-20T16:38:33-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rw-8-4-4-ssr-rsc-bold-moon-3936'
primary_region = 'lax'

[build]
  [build.args]
    NODE_VERSION = "20"

[deploy]
  release_command = '.fly/release.sh'

[env]
  # MIGRATE_ON_BOOT = 'true'
  PORT = '8910'
  REDWOOD_DISABLE_TELEMETRY = '1'

# [[mounts]]
#   source = 'data'
#   destination = '/data'

[http_service]
  internal_port = 8910
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
